---
- hosts: Buildserver
  become: true
  vars:
  - warName: java-example-0.0.1-SNAPSHOT.war
  - tomcat_version: 10.1.11
  - warRemotePath: /opt/apache-tomcat-{{ tomcat_version }}/webapps

  tasks:
  - name: Copy WAR to Remote server
    copy: src=target/{{ warName }} dest={{ warRemotePath }}/{{ warName }} owner=tomcat group=tomcat
